nelmio_api_doc:
    documentation:
        info:
            title: Publisher API
            description: API for publishing and more
            version: 1.0.0
    areas:
        path_patterns:
            - ^/api/v1
